//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Renting
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public int BillId { get; set; }
        public Nullable<int> RentId { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<int> TotalCost { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CompensationName { get; set; }
        public Nullable<int> Compensation { get; set; }
        public string CompensationDescript { get; set; }
    
        public virtual User User { get; set; }
        public virtual Rent Rent { get; set; }
    }
}
